pursuit_controler:
  ros__parameters:
    weight_goal_angle: 1.0
    weight_goal_linear: 1.0
    weight_smooth_angle: 1.0
    weight_smooth_linear: 1.0
    weight_smooth_wheel: 1.0
    weight_vel_angle: 1.0
    weight_vel_linear: 1.0
    iota: 1.0
    predict_horizon: 300
    sampling_number: 10
    control_cycle: 0.01
    max_input_value: [1.0, 1.0, 0.3]
    mu: [0.0, 0.0, 0.0]
    sigma: [1.0, 0.5, 0.2, 0.5, 1.0, 0.3, 0.2, 0.3, 1.0]