/daisha/pursuit_controler:
  ros__parameters:
    weight_goal_angle: 10.0
    weight_goal_linear: 50.0
    weight_smooth_angle: 1.0
    weight_smooth_linear: 1.0
    weight_smooth_wheel: 1.0
    weight_vel_angle: 1.0
    weight_vel_linear: 1.0
    iota: 0.1
    predict_horizon: 300
    sampling_number: 100
    control_cycle: 0.1
    max_input_value: [1.0, 1.0, 0.3]
    mu: [0.0, 0.0, 0.0]
    sigma: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]